jobs:
  xcodebuild:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: git submodule update --recursive --init
    
     
      - run:
          name: Build demo app for iOS
          command: set -o pipefail &&
            xcodebuild
              CODE_SIGNING_REQUIRED=NO
              CODE_SIGN_IDENTITY=""
              PROVISIONING_PROFILE=""
              -sdk "iphonesimulator"
              -destination 'platform=iOS Simulator,OS=latest,name=iPhone 8 Plus'
              -scheme "simd_sample"
              build |
            xcpretty --color --report junit
          path: ./simd_sample

  gradlebuild:
    docker:
      - image: flowkey/androidswift5:latest
    steps:
      - checkout
      - run: git submodule update --recursive --init
      - restore_cache:
          key: gradle_v1-{{ checksum "./samples/getting-started/android/build.gradle" }}
      - run:
          name: Build demo app for android
          command: ./gradlew assembleDebug
          path: ./samples/getting-started/android
      - save_cache:
          key: gradle_v1-{{ checksum "./samples/getting-started/android/build.gradle" }}
          paths:
              - /root/.gradle/

workflows:
  version: 2
  uikit:
    jobs:
      - xcodebuild
      #- gradlebuild